#!/usr/bin/python

import cgi
import sys
import mysql.connector
cnx=mysql.connector.connect(user="root",password="zlhn55",host="localhost",database="myDB")
cur=cnx.cursor()
cur.execute("select * from employee3") 
print"Content-Type: text/html" 
print"" 
print"<html>" 
print"<h2>CGI Script Output</h2>" 
print"<p>This page was generated by a Python CGI script------leezhu.</p>" 
print"<p>%s</p>" % (cur.fetchall())
print"</html>" 
